steps:
  <...>
  gctsCloneRepository:
    host: 'https://hcluks4hana.hcldigilabs.com:8001'
    client: '000'
    abapCredentialsId: 'AbapSystem'
    repository: 'myrepo'
    
    steps:
    gctsCreateRepository:
    host: 'https://hcluks4hana.hcldigilabs.com:8001'
    client: '000'
    abapCredentialsId: 'AbapSystem'
    repository: 'myrepo'
    remoteRepositoryURL: 'https://github.com/abhilashhaa/myrepo'
    role: 'SOURCE'
    vSID: 'FEF'

steps:
  <...>
  gctsDeploy:
    host: 'https://hcluks4hana.hcldigilabs.com:8001'
    client: '000'
    abapCredentialsId: 'AbapSystem'
    repository: 'myrepo'
    remoteRepositoryURL: "https://github.com/abhilashhaa/myrepo"
    role: 'SOURCE'
    vSID: 'FEF'
    branch: 'master'
    commit: 'commit'
    scope: 'scope'
    rollback: false
    configuration:
        dummyconfig: "dummyval"
